//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef _LIBSYCL_DEVICE_BINARY_STRUCTURES
#define _LIBSYCL_DEVICE_BINARY_STRUCTURES

#include <cstdint>

// Target identification strings
#define _LIBSYCL_DEVICE_BINARY_TARGET_TRIPLE_UNKNOWN "unknown-unknown-unknown"
// SPIR-V with 64-bit pointers
#define _LIBSYCL_DEVICE_BINARY_TARGET_SPIRV64 "spirv64-unknown-unknown"

// This is a replica of the EntryTy data structure in
// llvm/include/llvm/Frontend/Offloading/Utility.h.
struct EntryTy {
  /// Reserved bytes used to detect an older version of the struct, always zero.
  uint64_t Reserved = 0x0;
  /// The current version of the struct for runtime forward compatibility.
  uint16_t Version = 0x1;
  /// The expected consumer of this entry, e.g. SYCL or OpenMP.
  /// llvm::object::OffloadKind
  uint16_t Kind;
  /// Flags associated with the global.
  uint32_t Flags;
  /// The address of the global to be registered by the runtime.
  void *Address;
  /// The name of the symbol in the device image.
  char *SymbolName;
  /// The number of bytes the symbol takes.
  uint64_t Size;
  /// Extra generic data used to register this entry.
  uint64_t Data;
  /// An extra pointer, usually null.
  void *AuxAddr;
};

struct __sycl_tgt_device_image {
  uint16_t Version;
  uint8_t OffloadKind; // llvm::object::OffloadKind
  uint8_t ImageFormat; //  llvm::object::ImageKind
  const char *TripleString;
  /// A null-terminated string; target- and compiler-specific options
  /// which are suggested to use to "compile" program at runtime.
  const char *CompileOptions;
  /// A null-terminated string; target- and compiler-specific options
  /// which are suggested to use to "link" program at runtime.
  const char *LinkOptions;
  /// Pointer to the target code start
  const unsigned char *ImageStart;
  /// Pointer to the target code end
  const unsigned char *ImageEnd;
  /// the offload entry table
  EntryTy *EntriesBegin;
  EntryTy *EntriesEnd;
  // Property is not implemented now.
  void *PropertiesBegin;
  void *PropertiesEnd;
};

/// This struct is a record of all the device code that may be offloaded.
/// It must match the __tgt_bin_desc structure generated by
/// the clang-offload-wrapper tool when their `Version` field match.
struct __sycl_tgt_bin_desc {
  uint16_t Version;
  uint16_t NumDeviceBinaries;
  __sycl_tgt_device_image *DeviceImages;
  EntryTy *HostEntriesBegin;
  EntryTy *HostEntriesEnd;
};

// TODO: would be nice to include it from llvm/Object. It doesn't work now since
// I have to link LLVMObject to do that (linker error otherwise). Copy of
// llvm::object::OffloadKind.
/// The producer of the associated offloading image.
enum OffloadKind : uint16_t {
  OFK_None = 0,
  OFK_OpenMP = (1 << 0),
  OFK_Cuda = (1 << 1),
  OFK_HIP = (1 << 2),
  OFK_SYCL = (1 << 3),
  OFK_LAST = (1 << 4),
};

// Copy of llvm::object::ImageKind.
/// The type of contents the offloading image contains.
enum ImageKind : uint16_t {
  IMG_None = 0,
  IMG_Object,
  IMG_Bitcode,
  IMG_Cubin,
  IMG_Fatbinary,
  IMG_PTX,
  IMG_SPIRV,
  IMG_LAST,
};

static constexpr uint16_t LIBSYCL_SUPPORTED_OFFLOAD_BINARY_VERSION = 1;

// /// Types of device binary.
// enum DeviceBinaryType : uint8_t {
//   LIBSYCL_DEVICE_BINARY_TYPE_NONE = 0,   // undetermined
//   LIBSYCL_DEVICE_BINARY_TYPE_NATIVE = 1, // specific to a device
//   LIBSYCL_DEVICE_BINARY_TYPE_SPIRV = 2,
//   LIBSYCL_DEVICE_BINARY_TYPE_LLVMIR_BITCODE = 3,
//   LIBSYCL_DEVICE_BINARY_TYPE_COMPRESSED_NONE = 4
// };

#endif // _LIBSYCL_DEVICE_BINARY_STRUCTURES
